name: CI/CD
on: push
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and Push
        run: |
          docker buildx build \
            --no-cache \
            --push \
            -t 192.168.10.20:5000/node-app:latest \
            -t 192.168.10.20:5000/node-app:${GITHUB_SHA} .
      
      - name: Deploy
        run: |
          ansible-playbook ~/ansible/playbook.yml -i ~/ansible/inventory.ini --ask-become-pass
